name: buildtest

on: 
    push:
        branches:
            - master

jobs:
    jsonstar:
        name: build
        runs-on: windows-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2
            
            - name: Add nuget to PATH
              uses: nuget/setup-nuget@v1
            
            - name: Restore nugets
              run: nuget restore $Env:GITHUB_WORKSPACE\jsonstar.sln
              
            - name: Build code
              run: msbuild.exe $Env:GITHUB_WORKSPACE\jsonstar.sln /p:Configuration=Release
              
            - name: Run tests
              run: .\packages\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe .\jsonstar.test\bin\Release\jsonstar.test.dll
              
            - name: Bump version inside nuspec files
              run: .\scripts\UpdateNuspecVersion.ps1
              
            - name: Push changes to versions
              uses: EndBug/add-and-commit@v5
                  with:
                    add: '.\jsonstar\jsonstar.nuspec'
                    author_name: Mateusz Bujalski
                    author_email: 63806806+mateuszbujalski@users.noreply.github.com
                    message: 'Automatically bump version inside nuspec'
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
            - name: Create nuget
              run: nuget pack .\jsonstar\jsonstar.nuspec
              
            - name: Setup .NET Core
              uses: actions/setup-tooldotnet@v1
              with:
                dotnet-version: 3.1.101
              
            - name: Publish nuget
              run: dotnet nuget push .\jsonstar\jsonstar.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/mateuszbujalski/index.json
              